// <auto-generated />
namespace Smart_Piggy_Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initialset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialset));
        
        string IMigrationMetadata.Id
        {
            get { return "202205281838555_Initial-set"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
